### ISSUE TITLE
没有正常被释放

### ISSUE THREAD

**Issue by wuyongrui** [100mango/SwiftTimer#1]
场景是这样：ViewController --push--> SecondViewController,在SecondViewController的 viewDidLoad 中设置 timer:

```
    private var timer:SwiftTimer!

    override func viewDidLoad() {
        super.viewDidLoad()
        timer = SwiftTimer(interval: .seconds(1), repeats: true, handler: { (timer:SwiftTimer) in
            print("1")
        })
        timer.start()
    }
```

当点击 self.navigationItem.backBarButtonItem退出时，SecondViewController的 deinit 有调用到，但是 timer 的 deinit 没有被调用到(而且 print(1)还在正常 log)，如果手动添加 cancel 则可以log 到 SwiftTimer 的 deinit：

```
// SecondViewController.swift
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.timer.cancel() // 这个 cancel 只是调用 SwiftTimer 中 ·self.internalTimer.cancel()·
    }
```

环境：Xcode 8 beta 6

**Comment by 100mango** [comment]
@wuyongrui  已修复。你可以再测试一下，看看有什么问题。非常感谢。若有疏漏之处，还请多多指教。
