### ISSUE TITLE
duration not correct when suspend/resume after a while

### ISSUE THREAD

**Issue by DesmondDAI** [100mango/SwiftTimer#18]
I am using `SwiftTimer` and set interval to 1 second, and repeats = true. My event handler is:
```swift
if self.lastDate == nil {
    self.lastDate = Date()
    print("start date: \(self.lastDate!)")
    return
}            
let now = Date()
print("interval: \(now.timeIntervalSince(self.lastDate!))")
```
And `lastDate` is instance variable. My log is:
```
start date: 2017-11-20 09:47:28 +0000
interval: 0.299848973751068
interval: 1.29985100030899
interval: 2.29995399713516
interval: 3.29985398054123
interval: 4.29994195699692
interval: 5.29986900091171
interval: 6.29993796348572
interval: 7.29984599351883
interval: 8.29994297027588
interval: 9.30004799365997
interval: 10.2998879551888
interval: 11.2998659610748
interval: 12.2998409867287
interval: 13.2999309897423
interval: 14.2999339699745
interval: 15.2998569607735
interval: 16.2999249696732
interval: 18.357214987278
interval: 19.2994249463081
interval: 20.2998229861259
```
Note that the first interval is less than 1 second, and when I `suspend` after `interval: 16.2999` and `resume`, the `interval: 19.2999` after `interval: 18.357` **is not** 1 second. Seems like the implementation of GCD is a little out of my expectation. Do you know more detail about it? Thanks!

**Comment by 100mango** [comment]
Add leeway to SwiftTimer for greater accuracy. You can try the new implementation. @DesmondDAI
