### ISSUE TITLE
定时器回调Closure不被调用

### ISSUE THREAD

**Issue by beyondverage0908** [100mango/SwiftTimer#19]
如文档中定义的，我的测试是在定义的一个button的点击事件中触发的，如下的代码：

     @IBAction func runloopTimer(_ sender: Any) {
          let timer = SwiftTimer(interval: .seconds(2)) { (timer) in
              print("fire")
          }
          timer.start()
      }

发现SwiftTimer的Closure不会被调用。调试后发现由于`internalTimer.setEventHandler`设置了[weak self]，在点击事件方法结束的时候，SwiftTimer会调用`deinit`，销毁SwiftTimer对象，从而导致了SwiftTimer的Closure不会被调用。

so，为了保证timer不被销毁，需要将SwiftTimer声明为ViewController的一个成员变量，让timer被Controller持有，这样则SwiftTimer的Closure会成功调用，用Leaks检测也没有内存泄漏。如下的代码：

    class ViewController: UIViewController {
    ......

        private var timer: SwiftTimer? = nil   // 声明为Controller的成员变量
        timer = SwiftTimer(interval: .seconds(2), repeats: true, leeway: .seconds(0), queue: .main, handler: 
        { (timer) in
                   print("repeat fire")
               })
        timer?.start()

    .....
    }

你好，我是遵守README.md中定义usage去使用的，这是我哪里操作错了？或者是由于[weak self]的情况下，在方法结束后timer确实是会被`deinit`

**Comment by beyondverage0908** [comment]
还有一个问题，在您的源代码中，在deinit中，为什么是`internalTimer.resume()`，是否是`internalTimer.cancel()`

     deinit {
            if !self.isRunning {
                internalTimer.resume()
            }
       }

**Comment by 100mango** [comment]
的确是需要强持有Timer的，文档只是为了简化，我优化一下文档吧，避免歧义。感谢指出。至于为什么要resume，是为了避免crash。你可以自己查查原因。

**Comment by beyondverage0908** [comment]
thank you ~, crash的原因已经知道，谢谢
