### ISSUE TITLE
Xcode 8.0 (8A218a) 运行定时器没作用

### ISSUE THREAD

**Issue by huangboju** [100mango/SwiftTimer#2]

**Comment by 100mango** [comment]
麻烦可以给出更详细的描述吗？

**Comment by huangboju** [comment]
<img width="1280" alt="2016-09-22 11 25 03" src="https://cloud.githubusercontent.com/assets/14818224/18736182/401069a8-80b7-11e6-8508-29a6497d3721.png">

我复制的你的示例，但是没有进到回调里面啊

**Comment by 100mango** [comment]
注意Timer的生命周期。方法执行后,timer就销毁了。你要持有它。

**Comment by huangboju** [comment]
嗯，可以了
