### ISSUE TITLE
根本使用不起

### ISSUE THREAD

**Issue by IIIOS** [100mango/SwiftTimer#22]

**Comment by 100mango** [comment]
仔细看一下文档，谢谢。你这个 issue 提的一点不清晰。 我估计你是没有强引用Timer的原因。
文档已经写了：//We need to maintain a strong reference to SwiftTimer. When self dealloc, timer will dealloc too.

**Comment by yanxiaobing** [comment]
let timer = SwiftTimer.repeaticTimer(interval: .seconds(1)) { (handler) in
            print("test timer")
        }
timer.start()

有点懵逼   我也没启动成功
