### ISSUE TITLE
SwiftCountDownTimer is not working

### ISSUE THREAD

**Issue by zinwalin** [100mango/SwiftTimer#25]
`        let readyTimer = SwiftCountDownTimer(interval: .fromSeconds(1.0), times: 10) { timer, leftTimes in
            print("\(leftTimes)")
        }
        readyTimer.start()
`

print() has not been called when count down timer starts.

**Comment by 100mango** [comment]
We need to maintain a strong reference to SwiftTimer. When self dealloc, timer will dealloc too.
