### ISSUE TITLE
SwiftTimer.suspend crashes(Exception: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0))

### ISSUE THREAD

**Issue by laoyur** [100mango/SwiftTimer#3]
Xcode 8.1, iOS 10, simulator

```
    private var count = 0
    private var timer: SwiftTimer?
    
    @IBAction func stopClick(_ sender: Any) {
        print("timer will stop")
        self.timer?.suspend()
        self.timer = nil
    }
    @IBAction func startClick(_ sender: Any) {
        self.timer = SwiftTimer.repeaticTimer(interval: .seconds(1)) {
            tmr in
            self.count += 1
            print("\(self.count)")
        }
        timer?.start()
        print("timer started")
    }

```

output:
```
timer started
1
2
3
timer will stop
Exception: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```

**it works fine if I comment out  `self.timer?.suspend()`**

https://github.com/100mango/zen/issues/14

**Comment by laoyur** [comment]
my solution:
- add `private var isSuspended = false` to track the internalTimers' suspension state 
- call `internalTimer.resume()` in `deinit` if `isSuspended == true`
- use `internalTimer.activate()` rather than `internalTimer.resume()` in `SwiftTimer.start()`
- rename `SwiftTimer.suspend` into `SwiftTimer.pause` to prevent confusion, so users will know it is not necessary to call `pause` before set nil

**Comment by 100mango** [comment]
@laoyur According to Apple 
> Calling this function increments the suspension count of the object, and calling dispatch_resume decrements it. While the count is greater than zero, the object remains suspended, so you must balance each dispatch_suspend call with a matching dispatch_resume call.

Although Apple haven't  specifically point out that we can't dealloc a suspended source timer. But I think the crash is due to dealloc a suspended source timer.

So we can simply add resume in SwiftTimer's deinit to prevent this question. 

~~~swift
   deinit {
        if !isRunning {
            internalTimer.resume()
        }
    }
~~~

中文时间~  @laoyur ,我测试了一下，只要在deinit里添加resume的代码就没有问题了。你看看在你那种情况里，还有没问题，感谢指出这个漏洞。
