### ISSUE TITLE
示例需要修改

### ISSUE THREAD

**Issue by olddonkey** [100mango/SwiftTimer#4]
let timer = SwiftTimer(interval: .seconds(2)) {
    print("fire")
}

需要改成
let timer = SwiftTimer(interval: .seconds(2)) { _in
    print("fire")
}
否则编译器会报错，swift最近改的？但是在unit test里都是对的

**Comment by 100mango** [comment]
明白你的意思了。是指ReadME的代码把。是出于简略的情况才没写上的。以实际代码为准。
