### ISSUE TITLE
既然可以在子线程中操作，是不是应该加锁呢？

### ISSUE THREAD

**Issue by KittenYang** [100mango/SwiftTimer#5]
因为是用 gcd 实现的 timer 所以可以轻松实现子线程创建 timer，那是不是应该在 start ，suspend…这些方法前后加锁呢？

**Comment by 100mango** [comment]
SwiftTimer是非线程安全的。如果想在多线程环境中操作，建议加锁。不过我个人的经验是，Timer不适合在子线程开启。
