### ISSUE TITLE
carshed when use in iphone5

### ISSUE THREAD

**Issue by wesleyisme** [100mango/SwiftTimer#6]
I got a crash when I use SwiftTimer on iphone5;but it works fine on iphone5s,iphone6,se,plus etc.

when i call this function, app carshed,
 public static func fromSeconds(_ seconds: Double) -> DispatchTimeInterval {
     return .nanoseconds(Int(seconds * Double(NSEC_PER_SEC)))
    }
xcode log like this:
fatal error: Double value cannot be converted to Int because the result would be greater than Int.max

**Comment by 100mango** [comment]
I think you have input a big number?  If seconds * Double(NSEC_PER_SEC) > Int.max, then it will carsh.

**Comment by wesleyisme** [comment]
I  just input 10.0,whatever I input it always carsh. especially, this crash only occurred  on iPhone 5

**Comment by 100mango** [comment]
Thanks for your reply. I will test it soon.

**Comment by 100mango** [comment]
@wesleyisme Fix in dff9c5018d432553c4e88b8f2da806cffa60f1cb
